# Generated by Django 3.1 on 2020-09-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200916_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
